import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";


const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "600", "700"], 
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cairo.className}
      >
        {children}
      </body>
    </html>
  );
}
