import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";



const NotoSans =  Noto_Sans ({
  subsets: ["latin"],
  variable: "--font-noto-sans",
  weight: ['200' , '300', '400', '700'],

})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={NotoSans.className}
      >
        {children}
      </body>
    </html>
  );
}
